server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingservice
    username: postgres
    password: Saireddy@2610
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: rating-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true



